
#ifndef SHADER_H
#define SHADER_H

#include "color.h"

#define SHADER_PLAYER_IS_SELF_ON  EFFECT_BOLD_UNDERLINE_STRIKETHROUGH
#define SHADER_PLAYER_IS_SELF_OFF EFFECT_NO_BOLD_UNDERLINE_STRIKETHROUGH

#define SHADER_CHRISTMAS_LIGHTS_ON  EFFECT_ITALIC
#define SHADER_CHRISTMAS_LIGHTS_OFF EFFECT_NO_ITALIC

#endif
