
#ifndef SHADER_H
#define SHADER_H

#include "color.h"

#define SHADER_PLAYER_IS_SELF_ON  EFFECT_BOLD_UNDERLINE_STRIKETHROUGH
#define SHADER_PLAYER_IS_SELF_OFF EFFECT_NO_BOLD_UNDERLINE_STRIKETHROUGH

#define SHADER_CHRISTMAS_LIGHTS_ON  EFFECT_ITALIC
#define SHADER_CHRISTMAS_LIGHTS_OFF EFFECT_NO_ITALIC

#define SHADER_TOWER_ON  EFFECT_INVERSE
#define SHADER_TOWER_OFF EFFECT_NO_INVERSE

// ui

#define SHADER_UI COL_GREEN_DARK

#define SHADER_UI_DEAD_ON  EFFECT_STRIKETHROUGH
#define SHADER_UI_DEAD_OFF EFFECT_NO_STRIKETHROUGH

#endif
